import type { Architecture, Scenario } from "@systemforge/contracts";

const config = (
  overrides: Partial<Architecture["nodes"][number]["config"]>,
): Architecture["nodes"][number]["config"] => ({
  instances: 1,
  capacityRps: 10_000,
  baseLatencyMs: 5,
  maxConnections: 10_000,
  cacheHitRate: 0,
  replicas: 0,
  monthlyCostEur: 0,
  autoscale: false,
  maxInstances: 1,
  consistency: "strong",
  ...overrides,
});

export const DEFAULT_SCENARIO: Scenario = {
  schemaVersion: 1,
  id: "black-friday-checkout",
  title: "Black Friday Checkout",
  summary:
    "Keep checkout responsive while a cache failure and retry storm pressure the primary database.",
  mode: "guided",
  seed: 819_521,
  workload: {
    baseRps: 74_392,
    peakRps: 178_000,
    readRatio: 0.72,
    durationSeconds: 120,
    regions: [
      { name: "Europe", trafficShare: 0.45, roundTripMs: 28 },
      { name: "North America", trafficShare: 0.35, roundTripMs: 76 },
      { name: "Asia", trafficShare: 0.2, roundTripMs: 142 },
    ],
  },
  requirements: [
    {
      id: "p95",
      label: "p95 latency at or below 400 ms",
      metric: "p95LatencyMs",
      operator: "lte",
      target: 400,
      unit: "ms",
      visibility: "public",
      owner: "scenario",
    },
    {
      id: "availability",
      label: "Availability at or above 99.99%",
      metric: "availability",
      operator: "gte",
      target: 99.99,
      unit: "%",
      visibility: "public",
      owner: "scenario",
    },
    {
      id: "loss",
      label: "No confirmed order loss",
      metric: "dataLoss",
      operator: "eq",
      target: 0,
      unit: "orders",
      visibility: "public",
      owner: "scenario",
    },
    {
      id: "budget",
      label: "Monthly cost at or below EUR 140,000",
      metric: "monthlyCostEur",
      operator: "lte",
      target: 140_000,
      unit: "EUR",
      visibility: "public",
      owner: "scenario",
    },
  ],
  incidents: [
    {
      id: "traffic",
      atSecond: 24,
      kind: "traffic-spike",
      magnitude: 2.4,
      label: "Traffic +240%",
    },
    {
      id: "redis-down",
      atSecond: 40,
      kind: "cache-failure",
      magnitude: 1,
      label: "Redis node unavailable",
    },
    {
      id: "redis-back",
      atSecond: 82,
      kind: "cache-recovery",
      magnitude: 1,
      label: "Redis failover complete",
    },
  ],
};

export const DEFAULT_ARCHITECTURE: Architecture = {
  schemaVersion: 1,
  id: "checkout-v1",
  name: "Checkout architecture",
  nodes: [
    {
      id: "users",
      kind: "users",
      name: "Users",
      position: { x: 24, y: 178 },
      config: config({ capacityRps: 10_000_000 }),
    },
    {
      id: "cdn",
      kind: "cdn",
      name: "CDN",
      position: { x: 160, y: 178 },
      config: config({
        capacityRps: 500_000,
        baseLatencyMs: 12,
        cacheHitRate: 0.18,
        monthlyCostEur: 7_500,
      }),
    },
    {
      id: "lb",
      kind: "load-balancer",
      name: "Load Balancer",
      position: { x: 300, y: 178 },
      config: config({
        instances: 2,
        maxInstances: 2,
        capacityRps: 80_000,
        baseLatencyMs: 4,
        replicas: 1,
        monthlyCostEur: 1_100,
      }),
    },
    {
      id: "api",
      kind: "api",
      name: "API Gateway",
      position: { x: 445, y: 178 },
      config: config({
        instances: 24,
        maxInstances: 48,
        capacityRps: 10_000,
        baseLatencyMs: 18,
        monthlyCostEur: 900,
        autoscale: true,
      }),
    },
    {
      id: "cache",
      kind: "cache",
      name: "Redis Cluster",
      position: { x: 380, y: 32 },
      config: config({
        instances: 6,
        maxInstances: 6,
        capacityRps: 35_000,
        baseLatencyMs: 3,
        cacheHitRate: 0.91,
        replicas: 2,
        monthlyCostEur: 1_400,
        consistency: "eventual",
      }),
    },
    {
      id: "db",
      kind: "database",
      name: "PostgreSQL Primary",
      position: { x: 605, y: 72 },
      config: config({
        capacityRps: 75_000,
        baseLatencyMs: 24,
        maxConnections: 55_000,
        replicas: 3,
        monthlyCostEur: 33_000,
      }),
    },
    {
      id: "queue",
      kind: "queue",
      name: "Kafka Orders",
      position: { x: 470, y: 322 },
      config: config({
        instances: 3,
        maxInstances: 3,
        capacityRps: 18_000,
        baseLatencyMs: 8,
        replicas: 2,
        monthlyCostEur: 3_600,
        consistency: "eventual",
      }),
    },
    {
      id: "worker",
      kind: "worker",
      name: "Worker Pool",
      position: { x: 660, y: 322 },
      config: config({
        instances: 18,
        maxInstances: 36,
        capacityRps: 1_000,
        baseLatencyMs: 20,
        monthlyCostEur: 500,
        autoscale: true,
        consistency: "eventual",
      }),
    },
  ],
  edges: [
    { id: "e-users-cdn", source: "users", target: "cdn" },
    { id: "e-cdn-lb", source: "cdn", target: "lb" },
    { id: "e-lb-api", source: "lb", target: "api" },
    { id: "e-api-cache", source: "api", target: "cache" },
    { id: "e-api-db", source: "api", target: "db" },
    { id: "e-api-queue", source: "api", target: "queue" },
    { id: "e-queue-worker", source: "queue", target: "worker" },
    { id: "e-worker-db", source: "worker", target: "db" },
  ],
};
