import type { Architecture, Scenario } from "@systemforge/contracts";

const config = (
  overrides: Partial<Architecture["nodes"][number]["config"]>,
): Architecture["nodes"][number]["config"] => ({
  instances: 1,
  capacityRps: 10_000,
  baseLatencyMs: 5,
  maxConnections: 10_000,
  cacheHitRate: 0,
  replicas: 0,
  monthlyCostEur: 0,
  autoscale: false,
  maxInstances: 1,
  consistency: "strong",
  ...overrides,
});

export const DEFAULT_SCENARIO: Scenario = {
  schemaVersion: 1,
  id: "black-friday-checkout",
  title: "Black Friday Checkout",
  summary:
    "Keep checkout responsive while a cache failure and retry storm pressure the primary database.",
  mode: "guided",
  seed: 819_521,
  workload: {
    baseRps: 74_392,
    peakRps: 178_000,
    readRatio: 0.72,
    durationSeconds: 120,
    regions: [
      { name: "Europe", trafficShare: 0.45, roundTripMs: 28 },
      { name: "North America", trafficShare: 0.35, roundTripMs: 76 },
      { name: "Asia", trafficShare: 0.2, roundTripMs: 142 },
    ],
    concurrentUsers: 2_800_000,
    arrivalPattern: "bursty",
    clientTimeoutMs: 850,
    retryPolicy: {
      maxRetries: 3,
      backoffBaseMs: 120,
      jitter: true,
      retryOnTimeout: true,
    },
    requestMix: [
      {
        name: "Browse catalogue",
        share: 0.48,
        readRatio: 1,
        payloadKb: 18,
        computeMs: 3,
        databaseQueries: 1,
        cacheable: true,
        critical: false,
      },
      {
        name: "Read basket",
        share: 0.24,
        readRatio: 0.9,
        payloadKb: 9,
        computeMs: 5,
        databaseQueries: 2,
        cacheable: true,
        critical: false,
      },
      {
        name: "Confirm order",
        share: 0.2,
        readRatio: 0.15,
        payloadKb: 12,
        computeMs: 14,
        databaseQueries: 4,
        cacheable: false,
        critical: true,
      },
      {
        name: "Payment callback",
        share: 0.08,
        readRatio: 0.1,
        payloadKb: 5,
        computeMs: 9,
        databaseQueries: 2,
        cacheable: false,
        critical: true,
      },
    ],
  },
  requirements: [
    {
      id: "p95",
      label: "p95 latency at or below 400 ms",
      metric: "p95LatencyMs",
      operator: "lte",
      target: 400,
      unit: "ms",
      visibility: "public",
      owner: "scenario",
    },
    {
      id: "availability",
      label: "Availability at or above 99.99%",
      metric: "availability",
      operator: "gte",
      target: 99.99,
      unit: "%",
      visibility: "public",
      owner: "scenario",
    },
    {
      id: "loss",
      label: "No confirmed order loss",
      metric: "dataLoss",
      operator: "eq",
      target: 0,
      unit: "orders",
      visibility: "public",
      owner: "scenario",
    },
    {
      id: "budget",
      label: "Monthly cost at or below EUR 140,000",
      metric: "monthlyCostEur",
      operator: "lte",
      target: 140_000,
      unit: "EUR",
      visibility: "public",
      owner: "scenario",
    },
    {
      id: "durability",
      label: "Acknowledged-write durability at or above 99.999%",
      metric: "durabilityPercent",
      operator: "gte",
      target: 99.999,
      unit: "%",
      visibility: "public",
      owner: "scenario",
    },
    {
      id: "replica-lag",
      label: "Replica lag at or below 3 seconds",
      metric: "replicaLagMs",
      operator: "lte",
      target: 3_000,
      unit: "ms",
      visibility: "public",
      owner: "scenario",
    },
    {
      id: "queue-age",
      label: "Oldest asynchronous work at or below 10 seconds",
      metric: "maxQueueAgeMs",
      operator: "lte",
      target: 10_000,
      unit: "ms",
      visibility: "public",
      owner: "scenario",
    },
    {
      id: "residency",
      label: "EU customer PII remains in the EU",
      metric: "residencyViolations",
      operator: "eq",
      target: 0,
      unit: "writes",
      visibility: "public",
      owner: "scenario",
    },
  ],
  incidents: [
    {
      id: "traffic",
      atSecond: 24,
      kind: "traffic-spike",
      magnitude: 2.4,
      label: "Traffic +240%",
    },
    {
      id: "redis-down",
      atSecond: 40,
      kind: "cache-failure",
      magnitude: 1,
      label: "Redis node unavailable",
    },
    {
      id: "redis-back",
      atSecond: 82,
      kind: "cache-recovery",
      magnitude: 1,
      label: "Redis failover complete",
    },
    {
      id: "consumer-pressure",
      atSecond: 58,
      kind: "queue-consumer-slowdown",
      magnitude: 2.2,
      durationSeconds: 24,
      targetId: "worker",
      label: "Order consumers slowed",
    },
  ],
  domain: {
    acknowledgedWritesMustSurvive: true,
    preventOversell: true,
    piiRegion: "EU",
    staleReadToleranceSeconds: 2,
    maximumRecoverySeconds: 60,
  },
};

export const DEFAULT_ARCHITECTURE: Architecture = {
  schemaVersion: 1,
  id: "checkout-v1",
  name: "Checkout architecture",
  nodes: [
    {
      id: "users",
      kind: "users",
      name: "Users",
      position: { x: 24, y: 202 },
      config: config({ capacityRps: 10_000_000 }),
    },
    {
      id: "cdn",
      kind: "cdn",
      name: "CDN",
      position: { x: 168, y: 202 },
      config: config({
        capacityRps: 500_000,
        baseLatencyMs: 12,
        cacheHitRate: 0.18,
        monthlyCostEur: 7_500,
        behavior: {
          network: {
            bandwidthMbps: 160_000,
            rttMs: 9,
            jitterMs: 2,
            packetLossRate: 0.000_2,
            egressCostPerGb: 0.035,
          },
          resilience: {
            circuitBreaker: true,
            loadSheddingThreshold: 0.9,
          },
          topology: { region: "global", failureDomain: "edge" },
          operations: { complexityWeight: 2, managed: true },
        },
      }),
    },
    {
      id: "lb",
      kind: "load-balancer",
      name: "Load Balancer",
      position: { x: 318, y: 202 },
      config: config({
        instances: 2,
        maxInstances: 2,
        capacityRps: 80_000,
        baseLatencyMs: 4,
        replicas: 1,
        monthlyCostEur: 1_100,
        behavior: {
          compute: {
            cpuCores: 8,
            memoryGb: 16,
            concurrencyPerInstance: 120_000,
            serviceTimeMs: 2,
          },
          network: { bandwidthMbps: 80_000, rttMs: 2, jitterMs: 0.8 },
          resilience: {
            timeoutMs: 800,
            maxRetries: 0,
            jitter: true,
            circuitBreaker: true,
            loadSheddingThreshold: 0.92,
            bulkhead: true,
          },
          topology: { region: "EU", zone: "multi-az" },
          operations: { complexityWeight: 2, managed: true },
        },
      }),
    },
    {
      id: "api",
      kind: "api",
      name: "API Gateway",
      position: { x: 486, y: 202 },
      config: config({
        instances: 24,
        maxInstances: 48,
        capacityRps: 10_000,
        baseLatencyMs: 18,
        monthlyCostEur: 900,
        autoscale: true,
        behavior: {
          compute: {
            cpuCores: 8,
            memoryGb: 16,
            concurrencyPerInstance: 8_000,
            serviceTimeMs: 14,
            gcPauseMs: 18,
          },
          network: { bandwidthMbps: 25_000, rttMs: 3, jitterMs: 1.2 },
          resilience: {
            timeoutMs: 650,
            maxRetries: 2,
            backoffBaseMs: 120,
            jitter: true,
            circuitBreaker: true,
            loadSheddingThreshold: 0.88,
            bulkhead: true,
          },
          scaling: {
            minInstances: 12,
            targetUtilization: 0.68,
            cooldownSeconds: 12,
            startupSeconds: 7,
          },
          topology: { region: "EU", zone: "multi-az" },
          operations: { complexityWeight: 4, managed: false },
        },
      }),
    },
    {
      id: "cache",
      kind: "cache",
      name: "Redis Cluster",
      position: { x: 392, y: 28 },
      config: config({
        instances: 6,
        maxInstances: 6,
        capacityRps: 35_000,
        baseLatencyMs: 3,
        cacheHitRate: 0.91,
        replicas: 2,
        monthlyCostEur: 1_400,
        consistency: "eventual",
        behavior: {
          compute: { cpuCores: 8, memoryGb: 64, serviceTimeMs: 2 },
          network: { bandwidthMbps: 40_000, rttMs: 1, jitterMs: 0.4 },
          cache: {
            capacityGb: 256,
            ttlSeconds: 300,
            evictionPolicy: "lfu",
            hotKeyFraction: 0.04,
            warmupSeconds: 0,
          },
          storage: {
            replicationMode: "async",
            replicationLagMs: 24,
            failoverSeconds: 8,
          },
          topology: {
            region: "EU",
            zone: "multi-az",
            dataResidency: "EU",
          },
          operations: { complexityWeight: 4, managed: true },
        },
      }),
    },
    {
      id: "db",
      kind: "database",
      name: "PostgreSQL Primary",
      position: { x: 672, y: 72 },
      config: config({
        capacityRps: 75_000,
        baseLatencyMs: 24,
        maxConnections: 55_000,
        replicas: 3,
        monthlyCostEur: 33_000,
        behavior: {
          compute: {
            cpuCores: 96,
            memoryGb: 768,
            concurrencyPerInstance: 55_000,
            serviceTimeMs: 18,
          },
          network: { bandwidthMbps: 80_000, rttMs: 2, jitterMs: 0.8 },
          storage: {
            readIops: 280_000,
            writeIops: 160_000,
            diskThroughputMbps: 12_000,
            bufferHitRate: 0.94,
            lockContention: 0.03,
            partitions: 16,
            hotPartitionFraction: 0.08,
            replicationMode: "quorum",
            replicationLagMs: 12,
            failoverSeconds: 18,
          },
          resilience: {
            timeoutMs: 500,
            maxRetries: 1,
            backoffBaseMs: 150,
            jitter: true,
            circuitBreaker: true,
            loadSheddingThreshold: 0.9,
          },
          topology: {
            region: "EU",
            zone: "multi-az",
            dataResidency: "EU",
            failureDomain: "cluster",
          },
          operations: { complexityWeight: 7, managed: true },
        },
      }),
    },
    {
      id: "queue",
      kind: "queue",
      name: "Kafka Orders",
      position: { x: 482, y: 315 },
      config: config({
        instances: 3,
        maxInstances: 3,
        capacityRps: 18_000,
        baseLatencyMs: 8,
        replicas: 2,
        monthlyCostEur: 3_600,
        consistency: "eventual",
        behavior: {
          compute: { cpuCores: 16, memoryGb: 64, serviceTimeMs: 4 },
          network: { bandwidthMbps: 30_000, rttMs: 2, jitterMs: 0.7 },
          storage: {
            replicationMode: "quorum",
            replicationLagMs: 35,
            failoverSeconds: 12,
          },
          messaging: {
            partitions: 48,
            delivery: "at-least-once",
            retentionHours: 72,
            poisonMessageRate: 0.000_01,
            batchSize: 200,
          },
          topology: {
            region: "EU",
            zone: "multi-az",
            dataResidency: "EU",
          },
          operations: { complexityWeight: 6, managed: true },
        },
      }),
    },
    {
      id: "worker",
      kind: "worker",
      name: "Worker Pool",
      position: { x: 674, y: 315 },
      config: config({
        instances: 18,
        maxInstances: 36,
        capacityRps: 1_000,
        baseLatencyMs: 20,
        monthlyCostEur: 500,
        autoscale: true,
        consistency: "eventual",
        behavior: {
          compute: {
            cpuCores: 8,
            memoryGb: 16,
            concurrencyPerInstance: 2_500,
            serviceTimeMs: 20,
          },
          resilience: {
            timeoutMs: 2_000,
            maxRetries: 2,
            backoffBaseMs: 250,
            jitter: true,
            circuitBreaker: true,
            loadSheddingThreshold: 0.9,
          },
          scaling: {
            minInstances: 8,
            targetUtilization: 0.66,
            cooldownSeconds: 10,
            startupSeconds: 6,
          },
          topology: { region: "EU", zone: "multi-az" },
          operations: { complexityWeight: 4, managed: false },
        },
      }),
    },
  ],
  edges: [
    { id: "e-users-cdn", source: "users", target: "cdn" },
    { id: "e-cdn-lb", source: "cdn", target: "lb" },
    { id: "e-lb-api", source: "lb", target: "api" },
    { id: "e-api-cache", source: "api", target: "cache" },
    { id: "e-api-db", source: "api", target: "db" },
    { id: "e-api-queue", source: "api", target: "queue" },
    { id: "e-queue-worker", source: "queue", target: "worker" },
    { id: "e-worker-db", source: "worker", target: "db" },
  ],
};
